/* eslint-disable @next/next/no-img-element */
import {
  createUserWithEmailAndPassword,
  getAuth,
  signOut,
} from "firebase/auth";
import { addDoc, collection } from "firebase/firestore";
import { useRouter } from "next/router";
import React from "react";
import { useForm } from "react-hook-form";
import { toast, Toaster } from "react-hot-toast";
import FirebaseApp, { db } from "../../server/firebaseSDK";
import styles from "../../styles/Home.module.css";
import Head from "next/head";

export default function Login() {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm();
  const titlePage = "Daftar";
  const route = useRouter();
  const auth = getAuth(FirebaseApp);
  const daftar = async (data) => {
    try {
      await createUserWithEmailAndPassword(auth, data.email, data.password);
      await addDoc(collection(db, "users"), {
        password: data.password,
        email: data.email,
      });
      alert("Akun berhasil dibuat, silahkan login");

      await signOut(auth);
      route.replace("/login");
    } catch (error) {
      const errorCode = error.code;
      if (errorCode === "auth/email-already-in-use") {
        toast.error("email sudah dipakai");
      } else if (errorCode === "auth/weak-password") {
        toast.error("Password terlalu lemah");
      }
    }
  };

  return (
    <section>
      <Head>
        <title>{titlePage} | BPTD III Sumbar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className={styles.main}>
        <Toaster />

        <div className="mx-auto w-full lg:w-96">
          <div className="bg-white mx-5 p-5 shadow-xl rounded-lg">
            <h2 className="text-center mb-8 text-3xl font-extrabold text-slate-900">
              Daftar
            </h2>
            <form className="space-y-4" onSubmit={handleSubmit(daftar)}>
              <div>
                <input
                  className="mb-2 py-2 px-4 rounded-lg w-full shadow-xl text-slate-900"
                  id="email"
                  name="email"
                  type="email"
                  placeholder="Email"
                  {...register("email", { required: true })}
                />

                <input
                  className="py-2 px-4 rounded-lg w-full shadow-xl text-slate-900"
                  id="password"
                  name="password"
                  type="password"
                  placeholder="Password"
                  {...register("password", { required: true })}
                />
              </div>
              <div className="text-center"></div>
              <div>
                <button
                  type="submit"
                  className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-[#2D3082] focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                >
                  Daftar
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>{" "}
    </section>
  );
}
