/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable @next/next/no-img-element */
import { Loading } from "@nextui-org/react";
import dayjs from "dayjs";
import "dayjs/locale/id";
import relativeTime from "dayjs/plugin/relativeTime";
import { collection, getDocs, orderBy, query } from "firebase/firestore";
import Head from "next/head";
import React, { useEffect, useRef, useState } from "react";
import Layout from "../../components/layout";
import { useUser } from "../../context/user";
import { db } from "../../server/firebaseSDK";
import Image from "next/image";
import Link from "next/link";
import styles from "../../styles/Home.module.css";
import tambahpengaduan from "../../../public/tambahpengaduan.svg";
import { useRouter } from "next/router";
export default function LayouUser() {
  const user = useUser();
  const route = useRouter();
  dayjs.locale("id");
  dayjs.extend(relativeTime);
  const snapshot = useRef(null);
  const [isLoading, setIsloading] = useState(true);
  const getPengaduan = async () => {
    const querySnapshot = query(
      collection(db, "pengaduan"),
      orderBy("tanggal", "desc")
    );
    const gettt = await getDocs(querySnapshot);
    snapshot.current = gettt.docs;
    setTimeout(() => {
      setIsloading(false);
    }, 1000);
  };

  useEffect(() => {
    getPengaduan();
  }, []);

  if (isLoading) {
    return (
      <div className={styles.main}>
        <Loading color={"currentColor"} />
      </div>
    );
  } else {
    const post = snapshot.current;
    const data = Object.values(post);
    return (
      <Layout>
        <Head>
          <title>Pengaduan - BPTD III Sumbar</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo.png" />
        </Head>
        <main className="flex flex-col">
          <div className="flex justify-center gap-2">
            <Image className="w-5" src={tambahpengaduan} alt={"#"} />
            <Link
              href={!user ? "/login" : "/pengaduan/tambah-pengaduan"}
              className="text-center justify-self-center hover:bg-slate-900 hover:text-white py-1 px-2 rounded-lg"
            >
              Tambah Pengaduan
            </Link>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 py-5 px-5 gap-3">
            {data.map((e, i) => {
              const items = e.data();
              const isi = items.isi;
              const judul = items.judul;

              return (
                <div
                  key={i}
                  className="mx-auto w-full rounded-xl shadow-lg bg-white max-w-sm hover:cursor-pointer"
                  onClick={() => {
                    route.push(`/pengaduan/${e.id}`);
                  }}
                >
                  <div className="px-5 py-8">
                    <div className="justify-between mb-4">
                      <h5 className="text-gray-900 text-xl font-bold">
                        <div className={styles.truncate2}>{judul}</div>
                      </h5>

                      <h5
                        title={items.tanggal_berita}
                        className="text-gray-900 text-xs font-medium "
                      >
                        {dayjs(items.tanggal).fromNow()}
                      </h5>
                    </div>
                    <h1 className="text-gray-700  h-20 text-base mb-4">
                      <div className={styles.truncate3}>{isi}</div>
                    </h1>
                  </div>
                </div>
              );
            })}
          </div>
        </main>
      </Layout>
    );
  }
}
