/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable @next/next/no-img-element */
import { Loading } from "@nextui-org/react";
import dayjs from "dayjs";
import "dayjs/locale/id";
import relativeTime from "dayjs/plugin/relativeTime";
import { collection, getDocs, orderBy, query } from "firebase/firestore";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import Layout from "../../components/Layout";
import { db } from "../../server/firebaseSDK";
import styles from "../../styles/Home.module.css";

export default function LayouUser() {
  dayjs.locale("id");
  dayjs.extend(relativeTime);
  const snapshot = useRef(null);
  const [isLoading, setIsloading] = useState(true);

  const getDBFromFirestore = async () => {
    const querySnapshot = query(
      collection(db, "berita"),
      orderBy("tanggal", "desc")
    );
    const gettt = await getDocs(querySnapshot);
    snapshot.current = gettt.docs;
    setInterval(() => {
      setIsloading(false);
    }, 9000);
  };

  useEffect(() => {
    getDBFromFirestore();
  }, []);

  if (isLoading) {
    return (
      <div className={styles.main}>
        <Loading color={"currentColor"} />
      </div>
    );
  } else {
    const post = snapshot.current;
    const data = Object.values(post);
    return (
      <Layout>
        <Head>
          <title>Berita - BPTD III SUMBAR</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo.png" />
        </Head>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4  py-5 px-5 gap-3 mt-[84px]">
          {data.map((item) => {
            const itemm = item.data();

            return (
              <div
                key={item.id}
                className="mx-auto w-full rounded-xl shadow-lg bg-white max-w-sm"
              >
                <div className="overflow-clip rounded-t-lg rounded-br-3xl shadow-xl">
                  <img
                    className="object-cover h-48 w-full hover:scale-110 duration-1000"
                    src={`https://firebasestorage.googleapis.com/v0/b/bptd3sumbar-24e51.appspot.com/o/image%2F${itemm.gambar}?alt=media&token=e6aed1f9-4cad-4985-b739-dcf2fcd3e7de`}
                    alt={item.id}
                  />
                </div>

                <div className="px-5 py-8">
                  <div className="justify-between mb-4">
                    <h5 className="text-gray-900 text-xl font-bold">
                      <div className={styles.truncate2}>
                        {itemm.judul_berita}
                      </div>
                    </h5>
                    <div className="flex justify-between">
                      <h5 className="text-gray-900 text-xs font-medium ">
                        {itemm.penulis_berita}
                      </h5>
                      <h5
                        title={itemm.tanggal_berita}
                        className="text-gray-900 text-xs font-medium "
                      >
                        {dayjs(itemm.tanggal).fromNow()}
                      </h5>
                    </div>
                  </div>
                  <h1 className="text-gray-700  h-20 text-base mb-4">
                    <div className={styles.truncate3}>{itemm.isi_berita}</div>
                  </h1>

                  <Link
                    href={`/berita/${item.id}`}
                    className="shadow-xl hover:bg-slate-900 hover:text-slate-50 hover:duration-1000  text-xs py-2 px-4 rounded-lg"
                  >
                    Selengkapnya
                  </Link>
                </div>
              </div>
            );
          })}
        </div>
      </Layout>
    );
  }
}
