import dayjs from "dayjs";
import "dayjs/locale/id";
import relativeTime from "dayjs/plugin/relativeTime";
import { getAuth, updateProfile } from "firebase/auth";
import { getStorage, ref, uploadBytes } from "firebase/storage";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useState } from "react";
import { useForm } from "react-hook-form";
import app from "../../server/firebaseSDK";
import styles from "../../styles/Home.module.css";
import LayoutAdmin from "../../components/layout-admin";

export default function Admin() {
  const { register, handleSubmit, control } = useForm();

  const auth = getAuth();
  const user = auth.currentUser;

  const [imageUpload, setImageUpload] = useState();
  const route = useRouter();
  const storage = getStorage(app);
  const storageRef = ref(storage, `profile/${user.uid}`);
  dayjs.locale("id");
  dayjs.extend(relativeTime);
  const addDatafromDBFirestore = async (data) => {
    if (imageUpload == null) return;
    await uploadBytes(storageRef, imageUpload);
    try {
      updateProfile(auth.currentUser, {
        photoURL: `https://firebasestorage.googleapis.com/v0/b/bptd3sumbar-24e51.appspot.com/o/profile%2F${user.uid}?alt=media&token=2ed1037c-2a23-462f-ada1-262a451fcdd0`,
      });
      alert("profile berhasil diganti");
    } catch (error) {
      alert(error);
    }
  };
  /* This example requires Tailwind CSS v2.0+ */

  return (
    <LayoutAdmin>
      <Head>
        <title>Tambah Berita - Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className={styles.main}>
        <form
          className="flex flex-col"
          onSubmit={handleSubmit(addDatafromDBFirestore)}
        >
          <div>
            <label className="mr-2">Pilih Foto* :</label>
            <input
              className="mb-2"
              type="file"
              {...register("photoURL")}
              onChange={(event) => {
                setImageUpload(event.target.files[0]);
              }}
            />
          </div>

          <input
            className="bg-gray-800 mb-2 py-1 px-3 rounded-sm hover:cursor-pointer"
            type="submit"
          />
        </form>
      </div>
    </LayoutAdmin>
  );
}
