import { Loading } from "@nextui-org/react";
import { collection, getDocs, orderBy, query } from "firebase/firestore";
import Image from "next/image";
import React, { useEffect, useRef, useState } from "react";
import LayoutAdmin from "../../components/layout-admin";
import berita from "../../public/berita.svg";
import pengaduan from "../../public/pengaduan.svg";
import users from "../../public/users.svg";
import { db } from "../../server/firebaseSDK";
import Head from "next/head";
export default function Index() {
  const [isLoading, setIsloading] = useState(true);
  const Beritasnapshot = useRef(null);
  const Pengaduansnapshot = useRef(null);
  const Userssnapshot = useRef(null);
  const getDataBerita = async () => {
    const querySnapshot = query(
      collection(db, "berita"),
      orderBy("tanggal", "desc")
    );
    const gettt = await getDocs(querySnapshot);
    Beritasnapshot.current = gettt.docs;
    setInterval(() => {
      setIsloading(false);
    }, 1000);
  };
  const getDataPengaduan = async () => {
    const querySnapshot = query(
      collection(db, "pengaduan"),
      orderBy("tanggal", "desc")
    );
    const gettt = await getDocs(querySnapshot);
    Pengaduansnapshot.current = gettt.docs;
    setInterval(() => {
      setIsloading(false);
    }, 1000);
  };
  const getDataUsers = async () => {
    const querySnapshot = query(
      collection(db, "users"),
      orderBy("tanggal", "desc")
    );
    const gettt = await getDocs(querySnapshot);
    Userssnapshot.current = gettt.docs;
    setInterval(() => {
      setIsloading(false);
    }, 1000);
  };

  useEffect(() => {
    getDataBerita();
    getDataPengaduan();
    getDataUsers();
  }, []);

  return (
    <LayoutAdmin>
       <Head>
        <title>Admin - BPTD III SUMBAR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className="flex justify-evenly py-5 lg:py-10 rounded-lg shadow-xl">
        <div className="flex items-center gap-2">
          <Image src={berita} width={40} alt="#" />
          <div className="text-center text-sm md:text-base">
            <h1 className="font-semibold">
              {isLoading ? (
                <Loading color={"currentColor"} type="points" size="sm" />
              ) : (
                Object.values(Beritasnapshot.current).length
              )}
            </h1>
            <h1 className="font-medium">Berita</h1>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Image src={pengaduan} width={40} alt="#" />
          <div className="text-center text-sm md:text-base">
            <h1 className="font-semibold">
              {isLoading ? (
                <Loading color={"currentColor"} type="points" size="sm" />
              ) : (
                Object.values(Pengaduansnapshot.current).length
              )}
            </h1>
            <h1 className="font-medium">Pengaduan</h1>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Image src={users} width={40} alt="#" />
          <div className="text-center text-sm md:text-base">
            <h1 className="font-semibold">
              {isLoading ? (
                <Loading color={"currentColor"} type="points" size="sm" />
              ) : (
                Object.values(Userssnapshot.current).length
              )}
            </h1>
            <h1 className="font-medium">User</h1>
          </div>
        </div>
      </div>
    </LayoutAdmin>
  );
}
