import dayjs from "dayjs";
import "dayjs/locale/id";
import relativeTime from "dayjs/plugin/relativeTime";
import { addDoc, collection } from "firebase/firestore";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import { useForm } from "react-hook-form";
import Layout from "../../components/Layout";
import { db } from "../../server/firebaseSDK";
import styles from "../../styles/Home.module.css";

export default function Admin() {
  dayjs.locale("id");
  dayjs.extend(relativeTime);
  const route = useRouter();
  const { register, handleSubmit, control } = useForm();
  const addDatafromDBFirestore = async (data) => {
    
    await addDoc(collection(db, "berita"), {
      judul_berita: data.judul,
      isi_berita: data.isi,
      penulis_berita: data.penulis,
      tanggal_berita: dayjs().format("ddd, MMM D, YYYY HH:mm"),
      tanggal: dayjs().format(),
    });
    alert("Data berhasil ditambahkan");
    route.push("berita");
  };

  return (
    <Layout>
      <Head>
        <title>Admin - BPTD III SUMBAR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className={styles.main}>
        <form
          className="flex flex-col"
          onSubmit={handleSubmit(addDatafromDBFirestore)}
        >
          <input
            className="mb-2 py-1 px-3 rounded-sm"
            placeholder="Masukan judul"
            control={control}
            {...register("judul", { required: true })}
          />
          <input
            className="mb-2 py-1 px-3 rounded-sm"
            placeholder="Masukan isi"
            control={control}
            {...register("isi")}
          />{" "}
          <input
            className="mb-2 py-1 px-3 rounded-sm"
            placeholder="Masukan penulis"
            control={control}
            {...register("penulis")}
          />
          <input
            className="bg-gray-800 mb-2 py-1 px-3 rounded-sm hover:cursor-pointer"
            type="submit"
          />
          <input
            type="file"
            id="avatar"
            name="avatar"
            accept="image/png, image/jpeg"
          ></input>
        </form>

      
      </div>
    </Layout>
  );
}
