import { Dialog, Transition } from "@headlessui/react";
import { CheckIcon } from "@heroicons/react/outline";
import { Player } from "@lottiefiles/react-lottie-player";
import dayjs from "dayjs";
import "dayjs/locale/id";
import relativeTime from "dayjs/plugin/relativeTime";
import { getAuth } from "firebase/auth";
import { addDoc, collection } from "firebase/firestore";
import { getStorage, ref, uploadBytes } from "firebase/storage";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { Fragment, useState } from "react";
import { useForm } from "react-hook-form";
import { Toaster, toast } from "react-hot-toast";
import { v4 as uuidv4 } from "uuid";
import app, { db } from "../../server/firebaseSDK";
import styles from "../../styles/Home.module.css";
import LayoutAdmin from "../../components/LayoutAdmin";

export default function Admin() {
  const { register, handleSubmit, control, reset } = useForm();
  const uid = uuidv4();
  const auth = getAuth();
  const user = auth.currentUser;
  const [imageUpload, setImageUpload] = useState();
  const route = useRouter();
  const storage = getStorage(app);
  const [isLoading, setIsloading] = useState(false);
  const storageRef = ref(storage, `image/${uid}`);
  dayjs.locale("id");
  dayjs.extend(relativeTime);
  const addDatafromDBFirestore = async (data) => {
    const push = async () => {
      if (imageUpload == null) return;
      setIsloading(true);
      await uploadBytes(storageRef, imageUpload);
      await addDoc(collection(db, "berita"), {
        judul_berita: data.judul,
        isi_berita: data.isi,
        penulis_berita: user.displayName,
        tanggal_berita: dayjs().format("ddd, MMM D, YYYY HH:mm"),
        tanggal: dayjs().format(),
        gambar: storageRef.name,
      });
    };
    toast.promise(push(), {
      loading: "Saving...",
      success: <b>Settings saved!</b>,
      error: <b>Could not save.</b>,
    });
    reset();
  };
  return (
    <LayoutAdmin>
      <Head>
        <title>Tambah Berita - Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Toaster />
      <div className={styles.main}>
        <form
          className="flex flex-col"
          onSubmit={handleSubmit(addDatafromDBFirestore)}
        >
          <textarea
            className="  text-slate-900 resize-none mb-2 py-1 px-3 rounded-sm"
            placeholder="Masukan judul*"
            control={control}
            {...register("judul", { required: true })}
          />
          <div>
            <label className="mr-2">Pilih Foto* :</label>
            <input
              className="mb-2"
              type="file"
              {...register("gambar")}
              onChange={(event) => {
                setImageUpload(event.target.files[0]);
              }}
            />
          </div>
          <textarea
            rows={"6"}
            className="text-slate-900 mb-2 py-1 px-3 rounded-sm line-h"
            placeholder="Masukan isi*"
            control={control}
            {...register("isi")}
          />{" "}
          <input
            className="bg-gray-800 mb-2 py-1 px-3 rounded-sm hover:cursor-pointer"
            type="submit"
          />
        </form>
      </div>
    </LayoutAdmin>
  );
}
