import dayjs from "dayjs";
import "dayjs/locale/id";
import relativeTime from "dayjs/plugin/relativeTime";
import { getAuth } from "firebase/auth";
import { addDoc, collection } from "firebase/firestore";
import { getStorage, ref, uploadBytes } from "firebase/storage";
import Head from "next/head";
import React, { useState } from "react";
import { useForm } from "react-hook-form";
import { toast, Toaster } from "react-hot-toast";
import { v4 as uuidv4 } from "uuid";
import LayoutAdmin from "../../components/layout-admin";
import app, { db } from "../../server/firebaseSDK";
import styles from "../../styles/Home.module.css";
import { useRouter } from "next/router";

export default function Admin() {
  dayjs.locale("id");
  dayjs.extend(relativeTime);
  const { register, handleSubmit, control } = useForm();
  const uid = uuidv4();
  const auth = getAuth();
  const user = auth.currentUser;
  const [imageUpload, setImageUpload] = useState();
  const storage = getStorage(app);
  const storageRef = ref(storage, `image/${uid}`);
  const route = useRouter();

  const addDatafromDBFirestore = async (data) => {
    const push = async () => {
      if (imageUpload == null) return;
      await uploadBytes(storageRef, imageUpload);
      await addDoc(collection(db, "berita"), {
        judul_berita: data.judul,
        isi_berita: data.isi,
        penulis_berita: user.displayName,
        tanggal_berita: dayjs().format("ddd, MMM D, YYYY HH:mm"),
        tanggal: dayjs().format(),
        dilihat: 0,
        gambar: storageRef.name,
      });
      setInterval(() => {
        route.replace("/");
      }, 2000);
    };
    toast.promise(push(), {
      loading: "Mohon tunggu...",
      success: <b>Berhasil menambahkan berita</b>,
      error: <b>Terjadi kesalahan, silahkan coba lagi.</b>,
    });
  };
  return (
    <LayoutAdmin>
      <Head>
        <title>Tambah Berita - Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Toaster />
      <div className={styles.main}>
        <form
          className="flex flex-col mx-8"
          onSubmit={handleSubmit(addDatafromDBFirestore)}
        >
          <textarea
            className="mb-2 py-1 px-3 w-full rounded-lg mr-2 shadow-lg"
            placeholder="Masukan judul*"
            control={control}
            {...register("judul", { required: true })}
          />
          <div>
            <label className="mr-2">Pilih Foto* :</label>
            <input
              className="mb-2 py-1 px-3 w-full rounded-lg mr-2 shadow-lg"
              type="file"
              {...register("gambar")}
              onChange={(event) => {
                setImageUpload(event.target.files[0]);
              }}
            />
          </div>
          <textarea
            rows={"6"}
            className="mb-2 py-1 px-3 w-full rounded-lg mr-2 shadow-lg"
            placeholder="Masukan isi*"
            control={control}
            {...register("isi", { required: true })}
          />
          <input
            className="hover:bg-gray-900 w-full duration-1000 shadow-lg hover:text-white mb-2 py-1 px-3 rounded-lg hover:cursor-pointer"
            type="submit"
          />
        </form>
      </div>
    </LayoutAdmin>
  );
}
