import { getAuth, updateProfile } from "firebase/auth";
import Head from "next/head";
import { useForm } from "react-hook-form";
import { toast, Toaster } from "react-hot-toast";
import app from "../../server/firebaseSDK";
import styles from "../../styles/Home.module.css";

import LayoutAdmin from "../../components/layout-admin";
export default function Updatename() {
  const { register, handleSubmit, control, reset } = useForm();
  const auth = getAuth(app);
  const gantiName = async (data) => {
    const push = async () => {
      await updateProfile(auth.currentUser, {
        displayName: data.nama,
      });
    };

    toast.promise(push(), {
      loading: "Loading...",
      success: <b>Berhasil ganti nama!</b>,
      error: <b>Terjadi kesalaha, silahkan coba lagi!</b>,
    });

    reset();
  };
  return (
    <LayoutAdmin>
      <Toaster />
      <Head>
        <title>Ganti Nama - Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className={styles.main}>
        <form onSubmit={handleSubmit(gantiName)}>
          <input
            type={"text"}
            className="mb-2 text-slate-900 py-1 px-3 rounded-sm mr-2"
            placeholder="Nama baru*"
            control={control}
            {...register("nama", { required: true })}
          />
          <input
            className="bg-gray-800 mb-2 py-1 px-3 rounded-sm hover:cursor-pointer"
            type="submit"
          />
        </form>
      </div>
    </LayoutAdmin>
  );
}
