import { getAuth, updateProfile } from "firebase/auth";
import Head from "next/head";
import React from "react";
import { useForm } from "react-hook-form";
import app from "../../server/firebaseSDK";
import styles from "../../styles/Home.module.css";
import { Toaster, toast } from "react-hot-toast";
import { useRouter } from "next/router";
import { useToaster } from "react-hot-toast";
import LayoutAdmin from "../../components/LayoutAdmin";
export default function Updatename() {
  const route = useRouter();
  const { toasts, handlers } = useToaster();
  const { startPause, endPause } = handlers;
  const { register, handleSubmit, control, reset } = useForm();
  const auth = getAuth(app);
  const gantiName = async (data) => {
    updateProfile(auth.currentUser, {
      displayName: data.nama,
    });
    toast.success("Berhasil Ganti nama", { icon: "🎉" });
    reset();
  };
  return (
    <LayoutAdmin>
      <Head>
        <title>Ganti Nama - Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className={styles.main}>
        <div onMouseEnter={startPause} onMouseLeave={endPause}>
          {toasts
            .filter((toast) => toast.visible)
            .map((toast) => (
              <div key={toast.id} {...toast.ariaProps}>
                {toast.message}
              </div>
            ))}
        </div>
        <form onSubmit={handleSubmit(gantiName)}>
          <input
            type={"text"}
            className="mb-2 text-slate-900 py-1 px-3 rounded-sm mr-2"
            placeholder="Nama baru*"
            control={control}
            {...register("nama", { required: true })}
          />
          <input
            className="bg-gray-800 mb-2 py-1 px-3 rounded-sm hover:cursor-pointer"
            type="submit"
          />
        </form>
      </div>
    </LayoutAdmin>
  );
}
