/* eslint-disable @next/next/no-img-element */
import { getAuth, updateProfile } from "firebase/auth";
import Head from "next/head";
import React, { useState } from "react";
import { useForm } from "react-hook-form";
import app from "../../server/firebaseSDK";
import styles from "../../styles/Home.module.css";
import LayoutUser from "../../components/layout-user";
export default function Updatenameuser() {
  const { register, handleSubmit, control } = useForm();
  const [showAlert, setShowAlert] = useState(false);
  const auth = getAuth(app);
  const addDataImageHeader = async (data) => {
    await updateProfile(auth.currentUser, {
      displayName: data.nama,
    });
    setShowAlert(true);
  };
  return (
    <LayoutUser>
      <Head>
        <title>Ganti Nama - User</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className={styles.main}>
        {showAlert ? (
          <div className="absolute top-8 rounded-md bg-green-50 px-5 py-4">
            <div className="flex">
              <div className="flex-shrink-0"></div>
              <div className="ml-3">
                <p className="text-sm font-medium text-green-800">
                  Berhasil ganti nama
                </p>
              </div>
              <div className="ml-auto pl-3">
                <div className="-mx-1.5 -my-1.5">
                  <button
                    onClick={() => {
                      setShowAlert(false);
                    }}
                    type="button"
                    className="inline-flex bg-green-50 rounded-md p-1.5 text-green-500 hover:bg-green-100 focus:ring-offset-green-50 focus:ring-green-600"
                  >
                    <span className="sr-only">Dismiss</span>
                    <h1 className="px-2">x</h1>
                  </button>
                </div>
              </div>
            </div>
          </div>
        ) : (
          <></>
        )}
        <form onSubmit={handleSubmit(addDataImageHeader)}>
          <input
            type={"text"}
            className="mb-2 py-1 px-3 rounded-lg mr-2 shadow-lg"
            placeholder="Nama baru*"
            control={control}
            {...register("nama", { required: true })}
          />
          <input
            className="hover:bg-gray-900 duration-1000 shadow-lg hover:text-white mb-2 py-1 px-3 rounded-lg hover:cursor-pointer"
            type="submit"
          />
        </form>
      </div>
    </LayoutUser>
  );
}
