import Head from "next/head";
import React, { useState } from "react";
import ReactQuill from "react-quill";
import "react-quill/dist/quill.snow.css";
import Layout from "../../components/Layout";
import styles from "../../styles/Home.module.css";

export default function Kontak() {
  const [value, setValue] = useState("");
  return (
    <Layout>
      <Head>
        <title>Kontak - BPTD III SUMBAR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className={styles.main}>
        <ReactQuill theme="snow" value={value} onChange={setValue} />
        <code>{value}</code>
      </div>
    </Layout>
  );
}
