import { ThemeProvider } from "next-themes";
import Head from "next/head";
import AuthStateChangeProvider from "../context/auth";
import { UserProvider } from "../context/user";
import "../styles/globals.css";
import { useTheme } from "next-themes";
function MyApp({ Component, pageProps }) {
  const theme = useTheme();
  return (
    <>
      <Head>
        <title>BPTD III SUMBAR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <ThemeProvider enableSystem={false} forcedTheme={Component.theme || null}>
        <UserProvider>
          <AuthStateChangeProvider>
            <Component {...pageProps} />
          </AuthStateChangeProvider>
        </UserProvider>
      </ThemeProvider>
    </>
  );
}

export default MyApp;
