/* eslint-disable react-hooks/rules-of-hooks */
import Head from "next/head";
import Link from "next/link";
import React from "react";
import ComCarouselBerita from "../components/ComCarouselBerita";
import ComCarouselHeader from "../components/ComCarouselHeader";
import Layout from "../components/Layout";
import { useTheme } from "next-themes";
import LogoAtas from "../public/atas.png";
import Image from "next/image";
export default function Index() {
  const { theme, setTheme } = useTheme();
  return (
    <Layout>
      <Head>
        <title>BPTD III SUMBAR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div>
        <ComCarouselHeader />
        <div className=" dark:bg-slate-800 shadow-lg sm:h-[450px] md:h-[300px] lg:h-[300px] mx-5 my-4 rounded-md text-center">
          <div className="px-5">
            <div className="py-5  flex justify-between items-center">
              <h1 className="font-bold  mr-2">Berita Terbaru</h1>
              <Link href={"/berita"}>
                <a className="text-xs hover:underline">Lihat semua</a>
              </Link>
            </div>
            <div>
              <ComCarouselBerita />
            </div>
          </div>
        </div>
        <div className="dark:bg-slate-800 shadow-lg  mx-5 my-4 rounded-md text-center">
          <div className="px-8">
            <h1 className="py-5  font-bold ">Aplikasi & Layanan</h1>
            {/* <ComCarouselAplikasidanLayanan /> */}
            <h1 className="py-24">Coming Soon!</h1>
          </div>
        </div>
        <div className=" dark:bg-slate-800 shadow-lg sm:h-[450px] md:h-[300px] lg:h-[300px] mx-5 my-4 rounded-md text-center">
          <div className="px-5">
            <div className="py-5  flex justify-between items-center">
              <h1 className="font-bold mr-2">Postingan Dari Instagram</h1>
              <Link href={"/berita"}>
                <a className="text-xs hover:underline">Lihat semua</a>
              </Link>
            </div>
            <div>
              <ComCarouselBerita />
            </div>
          </div>
        </div>
        <div className=" dark:bg-slate-800 shadow-lg sm:h-[450px] md:h-[300px] lg:h-[300px] mx-5 my-4 rounded-md text-center">
          <div className="px-5">
            <div className="py-5  flex justify-between items-center">
              <h1 className="font-bold mr-2">Video Dari Youtube</h1>
              <Link href={"/berita"}>
                <a className="text-xs hover:underline">Lihat semua</a>
              </Link>
            </div>
            <div>
              <ComCarouselBerita />
            </div>
          </div>
        </div>
        <div className="fixed bottom-5 right-5 z-[9999] bg-slate-50 rounded-full shadow-xl h-[45px] w-[45px]">
          <Link href={"/"}>
            <a>
              <Image src={LogoAtas} alt={"3"} />
            </a>
          </Link>
        </div>
      </div>
    </Layout>
  );
}
