/* eslint-disable react-hooks/rules-of-hooks */
import { motion, useScroll, useSpring } from "framer-motion";
import Head from "next/head";
import Link from "next/link";
import ComCarouselHeader from "../components/Carousel/header";
import Layout from "../components/Layout";
import To_top from "../components/to-top";
import CarouselBerita from "../components/carousel/berita";
import CarouselYoutube from "../components/carousel/youtube";

export default function Index() {
  const { scrollYProgress } = useScroll();
  const scaleX = useSpring(scrollYProgress, {
    stiffness: 100,
    damping: 30,
    restDelta: 0.001,
  });

  return (
    <Layout cl>
      <motion.div
        className="progress-bar bg-gradient-to-r from-[#2D3082]  to-[#FBD107] bottom-0 h-1 z-[99999] rounded-full fixed left-0 right-0 origin-top"
        style={{ scaleX }}
      />
      <Head>
        <title>BPTD III SUMBAR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <div className="mt-[84px]">
        <ComCarouselHeader />
        <div className="shadow-xl mx-5 my-8 rounded-md text-center">
          <div className="flex flex-col justify-center items-center">
            <h1 className="font-bold">Berita Terpopuler</h1>
            <div className="m-4">
              <CarouselBerita />
            </div>
          </div>
        </div>
        <div className="shadow-xl mx-5 my-8 rounded-md text-center">
          <div className="flex flex-col justify-center items-center">
            <h1 className="font-bold">Postingan dari Instagram</h1>
            <div className="m-4">
             <CarouselYoutube/>
            </div>
          </div>
        </div>
        <div className="shadow-xl mx-5 my-8 rounded-md text-center">
          <div className="flex flex-col justify-center items-center">
            <h1 className="font-bold">Video dari Youtube</h1>
            <div className="m-4">
              <div className="grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 justify-center">
                <iframe
                  className="rounded-xl"
                  width="300"
                  height="200"
                  src="https://www.youtube.com/embed/3rht22WwF74"
                  title="YouTube video player"
                  frameBorder="0"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                  allowFullScreen
                />
                <iframe
                  className="rounded-xl"
                  width="300"
                  height="200"
                  src="https://www.youtube.com/embed/ckgWr8bBcYw"
                  title="YouTube video player"
                  frameBorder="0"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                  allowFullScreen
                ></iframe>
                <iframe
                  className="rounded-xl"
                  width="300"
                  height="200"
                  src="https://www.youtube.com/embed/9zYT5wBoNBE"
                  title="YouTube video player"
                  frameBorder="0"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                  allowFullScreen
                ></iframe>
                <iframe
                  className="rounded-xl"
                  width="300"
                  height="200"
                  src="https://www.youtube.com/embed/ihSGhPieF28"
                  title="YouTube video player"
                  frameBorder="0"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                  allowFullScreen
                ></iframe>
              </div>
            </div>
          </div>
        </div>

        <div className="shadow-xl mx-5 my-4 rounded-md text-center">
          <div className="px-5">
            <div className="py-5  flex justify-between items-center">
              <h1 className="font-bold mr-2">Aplikasi dan Layanan</h1>
              <Link href={"/berita"} className="text-xs hover:underline">
                Lihat semua
              </Link>
            </div>
            <div>
              <h1 className="py-24">Coming Soon!</h1>
            </div>
          </div>
        </div>
        <To_top />
      </div>
    </Layout>
  );
}
