import Head from "next/head";
import Layout from "../components/layout";
import styles from "../styles/Home.module.css";

export default function Kegiatan() {
  return (
    <Layout>
      <Head>
        <title>Kegiatan - BPTD III SUMBAR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <div className={styles.main}>Kegiatan</div>
    </Layout>
  );
}
