import Head from "next/head";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";

export default function Kontak() {
  return (
    <Layout>
      <Head>
        <title>Kontak - BPTD III SUMBAR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className={styles.main}>
        <h1>Kontak</h1>
      </div>
    </Layout>
  );
}
