import Layout from "../components/Layout/index";
import Styles from "../styles/Home.module.css";
import Head from "next/head";
export default function Kontak() {
  return (
    <Layout>
      <Head>
        <title>Kontak - BPTD III SUMBAR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className={Styles.main}>
        <h1>Kontak</h1>
      </div>
    </Layout>
  );
}
