/* eslint-disable @next/next/no-img-element */
import {
  getAuth, signInWithEmailAndPassword
} from "firebase/auth";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React from "react";
import { useForm } from "react-hook-form";
import { useUser } from "../context/user";
import app from "../server/firebaseSDK";
import styles from "../styles/Home.module.css";

export default function Login() {
  const user = useUser();
  const tittlePage = "Login";
  const route = useRouter();
  
  const { register, handleSubmit } = useForm();
  const auth = getAuth(app);

  const login = async (data) => {
    try {
      await signInWithEmailAndPassword(auth, data.email, data.password);
      if (data.email != "febriqgal@gmail.com") {
        route.replace("/user");
      } else {
        route.replace("/admin");
      }
    } catch (error) {
      if (error.code === "auth/wrong-password") {
        alert("Password Salah");
      } else if (error.code === "auth/user-not-found") {
        alert("Email tidak terdaftar");
      } else {
        alert("Tidak bisa login, coba beberapa saat lagi!");
      }
    }
  };

  return (
    <section>
      <Head>
        <title>{tittlePage}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className={styles.main}>
        <div className="sm:mx-auto sm:w-full sm:max-w-md">
          <img
            className="mx-auto h-12 w-auto hidden dark:flex"
            src="https://hubdat.dephub.go.id/static/images/logo_white.bae26e1b95c2.png"
            alt="Workflow"
          />
           <img
            className="mx-auto h-12 flex dark:hidden w-auto"
            src="  https://hubdat.dephub.go.id/static/images/logo_sites.cd63aebaf36b.png"
            alt="Workflow"
          />
        </div>
      
        <div className="mt-5 sm:mx-auto w-full sm:w-96">
          <div className="bg-white mx-5  px-5 py-5   shadow-xl rounded-lg">
            <h2 className="text-center mb-8 text-3xl font-extrabold text-slate-900">
              Login
            </h2>
            <form className="space-y-4" onSubmit={handleSubmit(login)}>
              <div>
                <input
                  className="mb-2 py-2 px-4 rounded-md bg-white w-full outline outline-1 text-slate-900"
                  id="email"
                  name="email"
                  type="email"
                  placeholder="Email"
                  {...register("email", { required: true })}
                />

                <input
                  className="py-2 px-4 rounded-md bg-white w-full outline outline-1 text-slate-900"
                  id="password"
                  name="password"
                  type="password"
                  placeholder="Password"
                  {...register("password", { required: true })}
                />
              </div>
              <div className="text-center">
                <Link href={"/lupapassword"}>
                  <a className="font-medium text-indigo-600 hover:text-indigo-500">
                    Lupa password?
                  </a>
                </Link>
              </div>

              <div>
                <Link href={"/daftar"}>
                  <a className="text-indigo-600 mb-2 w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 outline outline-1 outline-indigo-500">
                    Buat Akun
                  </a>
                </Link>
                <button
                  type="submit"
                  className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                >
                  Masuk
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
  );
}
