/* eslint-disable react/jsx-key */
/* eslint-disable @next/next/no-img-element */

import "animate.css";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Layout from "../components/Layout";
import LogoKanan from "../public/kanan.png";
export default function Organisasi() {
  const people = [
    {
      nama: "ARDONO, ATD, MT.",
      jabatan: "KEPALA BPTD TIPE B WIL. V PROV. SUMATERA BARAT",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "HERRY WANDA, Amd.LLAJ.,MAP",
      jabatan: "KEPALA SUB BAGIAN TATA USAHA",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "IKRA SURANTHA, ST., MT",
      jabatan: "KASI SARPRAS TRANSPORTASI JALAN",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "YUGO KRISTANTO, S.SiT",
      jabatan: "KASI LLAJ",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "ELBRIYAN SIRAIT, ST",
      jabatan: "KASI TRANSPORTASI SDP PERINTIS",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "SYAFRIZON, S.Sos",
      jabatan: "TERMINAL PENUMPANG TIPE A KELAS II SIMPANG AUR BUKIT TINGGI",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "HARI LEO AGUSTA, SE",
      jabatan: "TERMINAL PENUMPANG TIPE A KELAS III JATI PARIAMAN",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "PASDIAN, SH., MM",
      jabatan: "TERMINAL PENUMPANG TIPE A KELAS III SOLOK",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "WASIMAN",
      jabatan: "TERMINAL PENUMPANG TIPE A KELAS III KILIRAN JAO",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "HENDRI, SH",
      jabatan: "TERMINAL PENUMPANG TIPE A KELAS III ANAK AIR",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "FIRDAUS, S.Sos",
      jabatan: "UPPKB KELAS II LUBUK SELASIH",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "NURSYAFRIL BASAR, SH",
      jabatan: "UPPKB KELAS II SUNGAI LANGSAT",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "ALIZAR, SH",
      jabatan: "UPPKB KELAS II TANJUNG BALIK",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "HERWAN SOFDI, S.AP",
      jabatan: "UPPKB KELAS II AIR HAJI",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "B. TAUFIK K, SH",
      jabatan: "UPPKB KELAS II BERINGIN",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "AGUS SUMARSO, SE",
      jabatan: "PELABUHAN ANGKUTAN PENYEBERANGAN TELUK BUNGUS",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
  ];

  return (
    <Layout>
      <Head>
        <title>Organisasi - BPTD III SUMBAR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <ul
        role="list"
        className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 px-5 py-5 mt-[84px]"
      >
        {people.map((person) => (
          <li
            key={person.nama}
            className="col-span-1 flex flex-col text-center bg-white rounded-lg shadow-xl divide-y divide-gray-200"
          >
            <div className="flex-1 flex flex-col p-8  ">
              <div className="w-32 h-32 flex-shrink-0 bg-gray-800 mx-auto rounded-full" />
              <h3 className="mt-6 text-gray-900 text-sm font-bold">
                {person.nama}
              </h3>
              <dl className="mt-1 flex-grow flex flex-col justify-between">
                <dt className="sr-only">Title</dt>
                <dt className="sr-only">Role</dt>
                <dd className="mt-3">
                  <span className="px-2 py-1 text-slate-500 text-xs font-semibold">
                    {person.jabatan}
                  </span>
                </dd>
              </dl>
            </div>
            <div>
              <div className="-mt-px flex divide-x divide-gray-200">
                <div className="-ml-px w-0 flex-1 flex">
                  <Link
                    href={`tel:${person.telephone}`}
                    className="relative w-0 flex-1 inline-flex items-center justify-center py-4 text-sm text-gray-700 font-medium border border-transparent rounded-br-lg hover:text-gray-500"
                  >
                    <Image
                      alt={`${person.nama}`}
                      src={LogoKanan}
                      width={25}
                      height={25}
                    />
                    Selengkapnya
                  </Link>
                </div>
              </div>
            </div>
          </li>
        ))}
      </ul>
    </Layout>
  );
}
