import { Dialog, Transition } from "@headlessui/react";
import { CheckIcon } from "@heroicons/react/outline";
import dayjs from "dayjs";
import "dayjs/locale/id";
import relativeTime from "dayjs/plugin/relativeTime";
import { getAuth } from "firebase/auth";
import { addDoc, collection } from "firebase/firestore";
import { getStorage, ref, uploadBytes } from "firebase/storage";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { Fragment, useState } from "react";
import { useForm } from "react-hook-form";
import { v4 as uuidv4 } from "uuid";
import protectpengduan from "../hoc/protectpengduan";
import app, { db } from "../server/firebaseSDK";
import styles from "../styles/Home.module.css";
import { toast, Toaster } from "react-hot-toast";

const Tambahpengaduan = () => {
  const [isDisable, setDisable] = useState(false);
  const { register, handleSubmit, control, reset } = useForm();
  const uid = uuidv4();
  const auth = getAuth();
  const user = auth.currentUser;
  const [imageUpload, setImageUpload] = useState();
  const storage = getStorage(app);
  const storageRef = ref(storage, `image/${uid}`);
  dayjs.locale("id");
  dayjs.extend(relativeTime);
  const addDatafromDBFirestore = async (data) => {
    const push = async () => {
      if (imageUpload == null) return;
      uploadBytes(storageRef, imageUpload).then((snapshot) => {});
      await addDoc(collection(db, "pengaduan"), {
        judul_pengaduan: data.judul,
        isi_pengaduan: data.isi,
        penulis_pengaduan: user.displayName,
        tanggal_pengaduan: dayjs().format("ddd, MMM D, YYYY HH:mm"),
        tanggal: dayjs().format(),
        email: user.email,
        gambar: `https://firebasestorage.googleapis.com/v0/b/bptd3sumbar-24e51.appspot.com/o/image%2F${storageRef.name}?alt=media&token=fc601c2a-1e0a-4810-8d2c-1826c3923d36`,
      });
      reset();
    };
    toast.promise(push(), {
      loading: "Mohon tunggu...",
      success: <b>Berhasil menambah pengaduan</b>,
      error: <b>Terjadi kesalahan, silahkan coba lagi.</b>,
    });
  };

  return (
    <div className={styles.main}>
      <Head>
        <title>Tambah Berita - Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Toaster />
      <form
        className="flex flex-col w-full sm:w-[500px] px-5"
        onSubmit={handleSubmit(addDatafromDBFirestore)}
      >
        <textarea
          className="resize-none mb-2 py-1 px-3 w-full rounded-lg shadow-lg"
          placeholder="Masukan judul*"
          control={control}
          disabled={isDisable}
          {...register("judul", { required: true })}
        />
        <div>
          <label className="mr-2">Pilih Foto* :</label>
          <input
            className="mb-2 shadow-lg p-2 w-full"
            type="file"
            disabled={isDisable}
            {...register("gambar", { required: false })}
            onChange={(event) => {
              setImageUpload(event.target.files[0]);
            }}
          />
        </div>
        <textarea
          rows={"6"}
          className="mb-2 py-1 px-3 rounded-lg w-full line-h shadow-lg"
          placeholder="Masukan isi*"
          control={control}
          disabled={isDisable}
          {...register("isi")}
        />{" "}
        <input
          className="hover:bg-gray-900 duration-1000 shadow-lg hover:text-white mb-2 py-2 px-3 rounded-lg hover:cursor-pointer"
          type="submit"
        />
      </form>
    </div>
  );
};
export default protectpengduan(Tambahpengaduan);
